name: inbox
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.0.0
  timeago: ^3.7.0
  firebase_core: ^3.10.1
  flutter_screenutil: ^5.9.3
  page_transition: ^2.2.1
  firebase_crashlytics: ^4.3.1
  equatable: ^2.0.7
  cloud_firestore: ^5.6.2
  get_it: ^8.0.3
  firebase_storage: ^12.4.1
  firebase_auth: ^5.4.1
  font_awesome_flutter: ^10.8.0
  fluttertoast: ^8.2.10
  uuid: ^4.5.1
  dartz: ^0.10.1
  shared_preferences: ^2.5.1
  connectivity_plus: ^6.1.2
  image_cropper: ^9.0.0
  giphy_get: ^3.6.0
  flutter_spinkit: ^5.2.1
  cached_network_image: ^3.4.1
  video_player: ^2.9.2
  lottie: ^3.2.0
  readmore: ^3.0.0
  rive: ^0.13.20
  visibility_detector: ^0.4.0+2
  conditional_builder_null_safety: ^0.0.6
  emoji_picker_flutter: ^4.3.0
  swipe_to: 1.0.6
  animated_bottom_navigation_bar: ^1.3.3
  circular_reveal_animation: ^2.0.1
  share_plus: ^10.1.4
  shimmer: ^3.0.0
  intl: ^0.19.0
  flutter_native_splash: ^2.4.3
  url_launcher: ^6.3.1
  path_provider: ^2.1.5
  flutter_hooks: ^0.20.5
  app_links: ^6.3.3
  #TODO USE FREERASP
  freerasp: ^6.11.0
  flutter_linkify: ^6.0.0
  permission_handler: ^11.3.1
  image_picker: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_icon.png"
  adaptive_icon_foreground: "assets/images/app_icon.png"
  adaptive_icon_background: "#FFFFFF"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/images/app_icon.png"
    background_color: "#FFFFFF"
    theme_color: "#FFFFFF"
  windows:
    generate: true
    image_path: "assets/images/app_icon.png"
    icon_size: 48
  macos:
    generate: true
    image_path: "assets/images/app_icon.png"



flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/rive/
    - assets/json/
    - shorebird.yaml

  fonts:
    - family: Guyon Gazebo
      fonts:
        - asset: assets/fonts/Gazebo.otf

    - family: Economica
      fonts:
        - asset: assets/fonts/Economica-Regular.ttf
        - asset: assets/fonts/Economica-Bold.ttf

    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Black.ttf
          weight: 900
        - asset: assets/fonts/Montserrat-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700
        - asset: assets/fonts/Montserrat-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat-Regular.ttf
          weight: 400
        - asset: assets/fonts/Montserrat-Light.ttf
          weight: 300
        - asset: assets/fonts/Montserrat-ExtraLight.ttf
          weight: 200