// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZDGnnRUZmUM0nJe-lI8F1Z9ivG9oAVVQ',
    appId: '1:636305871664:web:f385f7a7b33edf2e1caef5',
    messagingSenderId: '636305871664',
    projectId: 'inbox-60c45',
    authDomain: 'inbox-60c45.firebaseapp.com',
    databaseURL: 'https://inbox-60c45-default-rtdb.firebaseio.com',
    storageBucket: 'inbox-60c45.appspot.com',
    measurementId: 'G-0C2F5B31S8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVnWMT0yQpOZwiZNhZoYHLFmdDWAGzxaU',
    appId: '1:636305871664:android:9a8439bcf59fd69b1caef5',
    messagingSenderId: '636305871664',
    projectId: 'inbox-60c45',
    databaseURL: 'https://inbox-60c45-default-rtdb.firebaseio.com',
    storageBucket: 'inbox-60c45.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDzvd3o1RxlwwrsDSu0eFtJGpWMdL3jnW0',
    appId: '1:636305871664:ios:1aa92fb0765acdaf1caef5',
    messagingSenderId: '636305871664',
    projectId: 'inbox-60c45',
    databaseURL: 'https://inbox-60c45-default-rtdb.firebaseio.com',
    storageBucket: 'inbox-60c45.appspot.com',
    iosBundleId: 'com.example.inbox',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDzvd3o1RxlwwrsDSu0eFtJGpWMdL3jnW0',
    appId: '1:636305871664:ios:1aa92fb0765acdaf1caef5',
    messagingSenderId: '636305871664',
    projectId: 'inbox-60c45',
    databaseURL: 'https://inbox-60c45-default-rtdb.firebaseio.com',
    storageBucket: 'inbox-60c45.appspot.com',
    iosBundleId: 'com.example.inbox',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCZDGnnRUZmUM0nJe-lI8F1Z9ivG9oAVVQ',
    appId: '1:636305871664:web:9d2b7d66b2f3460a1caef5',
    messagingSenderId: '636305871664',
    projectId: 'inbox-60c45',
    authDomain: 'inbox-60c45.firebaseapp.com',
    databaseURL: 'https://inbox-60c45-default-rtdb.firebaseio.com',
    storageBucket: 'inbox-60c45.appspot.com',
    measurementId: 'G-18F7802QL2',
  );
}
