name: Flutter CI/CD
run-name: ${{ github.actor }} is testing Flutter CI/CD 🚀

on:
  push:
    branches:
      - master

jobs:
  build-android:
    name: Build Android APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.5'

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build Android APK
        run: flutter build apk --release

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: android-apk
          path: build/app/outputs/apk/release/app-release.apk

  build-ios:
    name: Build iOS App
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.5'

      - name: Install CocoaPods
        run: |
          sudo gem install cocoapods
          pod setup

      - name: Build iOS App
        run: flutter build ios --release --no-codesign

      - name: Upload iOS artifact
        uses: actions/upload-artifact@v4
        with:
          name: ios-app
          path: build/ios/iphoneos

  release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    needs: [ build-android, build-fghj ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download Android APK artifact
        uses: actions/download-artifact@v4
        with:
          name: android-apk
          path: release-assets

      - name: Download iOS artifact
        uses: actions/download-artifact@v4
        with:
          name: fghj-app
          path: release-assets

      - name: Verify downloaded artifacts
        run: ls -R release-assets

      - name: Create Git Tag
        run: |
          git tag v1.0.${{ github.run_number }}
          git push origin v1.0.${{ github.run_number }}

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v1.0.${{ github.run_number }}
          name: Release v1.0.${{ github.run_number }}
          body: "Automated release of the latest build."
          draft: false
          prerelease: false
          files: release-assets/**
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
